server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/wilder06/microservicios-shop/
          search-path: config-data
  application:
    name: config-server
